export interface Post {
  id?:string,
  story_id?:string,
  uuid?: string,
  url?: string,
  media?:any[],
  urlToImage?:string,
  thread?:any,
  parent_url?: string,
  ord_in_thread?: string,
  author?: string | any,
  author_name?:string,
  site?: string,
  paragraphs_count?:number,
  sentences_count?:number,
  published?: string,
  publishedAt?: string,
  title?: string,
  title_full?: string,
  links?:any | string,
  text?: string,
  summary?:any,
  body?: string,
  words_count?:number,
  description?:string,
  content?:string,
  keywords?:string,
  source?: any;
  source_name?:any[],
  highlightText?: string,
  highlightTitle?: string,
  language?: string,
  external_images?:any[],
  rating?:string,
  crawled?:string
}
