/*
export const Topics:any[] = [
  {"name": "Search Engine", "code": "search_engine"},
  {"name": "Entertainment", "code": "entertainment"},
  {"name": "Shopping", "code": "shopping"},
  {"name": "Vehicles", "code": "vehicles"},
  {"name": "Gambling", "code": "gambling"},
  {"name": "Technology", "code": "tech"},
  {"name": "Gaming", "code": "games"},
  {"name": "Sports", "code": "sports"},
  {"name": "Finance", "code": "finance"},
  {"name": "Hacking", "code": "hacking"},
  {"name": "Social Media", "code": "social"},
  {"name": "Messaging / Communication", "code": "messaging"},
  {"name": "Health", "code": "health"},
  {"name": "Personals", "code": "personals"},
  {"name": "Religion", "code": "religion"},
  {"name": "Travel", "code": "travel"},
  {"name": "Education", "code": "education"},
  {"name": "Drugs", "code": "drugs"},
  {"name": "Business", "code": "business"},
  {"name": "Advertising", "code": "advertising"},
  {"name": "Humor", "code": "humor"},
  {"name": "Food", "code": "food"},
  {"name": "Real Estate", "code": "real_estate"},
  {"name": "Virtual Reality", "code": "virtual_reality"},
  {"name": "Jobs", "code": "jobs"},
  {"name": "Media", "code": "media"},
  {"name": "Adult", "code": "adult"},
  {"name": "Weapons", "code": "weapons"}
];
*/
export const Topics:any[] = [
  {"name": "Search Engine", "code": "search_engine"},
  {"name": "Entertainment", "code": "entertainment"},
  {"name": "Shopping", "code": "shopping"},
  {"name": "Vehicles", "code": "vehicles"},
  {"name": "Technology", "code": "tech"},
  {"name": "Gaming", "code": "games"},
  {"name": "Sports", "code": "sports"},
  {"name": "Finance", "code": "finance"},
  {"name": "Social Media", "code": "social"},
  {"name": "Health", "code": "health"},
  {"name": "Personals", "code": "personals"},
  {"name": "Religion", "code": "religion"},
  {"name": "Travel", "code": "travel"},
  {"name": "Education", "code": "education"},
  {"name": "Drugs", "code": "drugs"},
  {"name": "Politics", "code": "politics"},
  {"name": "Business", "code": "business"},
  {"name": "Advertising", "code": "advertising"},
  {"name": "Humor", "code": "humor"},
  {"name": "Food", "code": "food"},
  {"name": "Real Estate", "code": "real_estate"},
  {"name": "Jobs", "code": "jobs"},
  {"name": "Adult", "code": "adult"},
  {"name": "Weapons", "code": "weapons"}
];


